apiVersion: apps/v1
kind: Deployment
metadata:
  name: onefusion-web-equipment
  namespace: onefusion-default
spec:
  replicas: 1
  selector:
    matchLabels:
      project.cpaas.io/name: onefusion
      service.cpaas.io/name: deployment-onefusion-web-equipment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cpaas.io/creator: yinxiaoyun@cmict.chinamobile.com
      creationTimestamp: null
      labels:
        project.cpaas.io/name: onefusion
        service.cpaas.io/name: deployment-onefusion-web-equipment
    spec:
      containers:
        - image: cmict-docker.pkg.coding.dev.ict.cmcc/onefusion/onefusion/onefusion-web-equipment:latest
          imagePullPolicy: Always
          name: onefusion-web-equipment
          ports:
            - containerPort: 89
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: cm
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: portal-web-cm
          name: cm
